# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: flutter-android-build
        # You may pin to the exact commit or the version.
        # uses: NiklasLehnfeld/flutter-android-build-action@95d74edc2e862e6f8c73f7bbfad84acc16740abb
        uses: NiklasLehnfeld/flutter-android-build-action@v1
        with:
          # If set to `true`, it will run release builds, otherwise debug builds
          release: true # optional
          # apk | aab | both
          build-type: apk # optional, default is both
          # Base64 encoded keystore.jks, required if release is true
          keystore: false # optional, default is 
          # keystore password, required if release is true
          keystore-pwd: "" # optional, default is 
          # key password, required if release is true
          key-pwd: "" # optional, default is 
